module.exports = {
    SUCCESS: 'success',
    FAIL: 'fail',
    ADMIN: 'Admin',
    ATTACHMENT:'attachments',
    PROFILE_PIC:'photo',
    SIGNATURE:'signature',
    PENDING: 'Pending',
    ACTIVE: 'Active',
    DEACTIVE: 'Deactive',
    COMPANY: 'company',
    ERROR: 'error',
    CREATED: "created",
    READ: "read",
    LOCAL_URL: "http://localhost:4000/",
    AUTHENTICATION_TOKEN_FAIL:"authentication fail",
    NO_TOKEN_PROVIDED:"access token not provided",
    MESSAGE: {
        EMAIL_INVALID: 'Incorrect Email',
        PASSOWRD_INVALID: 'Incorrect Password',
        REQUIRED_FIELDS_MISSING: 'Required fields are missing!',
        EMAIL_ALREADY_EXIT: 'Email Already Exist',
        NOT_REGISTERED_USER: 'You are not registered user',
        INVALID_EMAIL: 'Invalid Email',
        LOGIN_SUCCESS: 'Login success!',
        PROFILE_PHOTO_UPLODED: 'Profile photo uploaded successfully!',
    },
    FOLDER_USER_IMG: "uploaded_documents/user_images/",
}