module.exports = {
    SUCCESS: 'success',
    FAIL: 'fail',
    ADMIN: 'Admin',
    ATTACHMENT:'attachments',
    PROFILE_PIC:'photo',
    SIGNATURE:'signature',
    PENDING: 'Pending',
    ACTIVE: 'Active',
    DEACTIVE: 'Deactive',
    COMPANY: 'company',
    ERROR: 'error',
    CREATED: "created",
    READ: "read",
    LOCAL_URL: "http://localhost:4000/",
    AUTHENTICATION_TOKEN_FAIL:"authentication fail",
    NO_TOKEN_PROVIDED:"access token not provided",
    MESSAGE: {
        EMAIL_INVALID: 'Incorrect Email',
        PASSOWRD_INVALID: 'Incorrect Password',
        REQUIRED_FIELDS_MISSING: 'Required fields are missing!',
        EMAIL_ALREADY_EXIT: 'Email Already Exist',
        NOT_REGISTERED_USER: 'You are not registered user',
        INVALID_EMAIL: 'Invalid Email',
        LOGIN_SUCCESS: 'Login success!',
        PROFILE_PHOTO_UPLODED: 'Profile photo uploaded successfully!',
        USER_NOT_FOUND: 'User not found!',
        LOGIN_SUCESSFULLY: 'Login success!',
        REGISTER_SUCCESSFULLY:'Register successfully!!!',
        EMAIL_REQUIRED: 'Email address is required',
        EMAIL_INVALID: 'Incorrect Email',
        PASSOWRD_INVALID: 'Incorrect Password',
        REQUIRED_FIELDS_MISSING: 'Required fields are missing!',
        EMAIL_EXIST: 'Email already exists please try with another email!',
        CATEGORY_RECORD_EXIST: 'You can not delete this Category. Please first delete existing records with this Category.',
        NOT_FOUND_BY_ID: 'not found with ID ',
        DATA_FOUND: 'Data found',
        DATA_NOT_FOUND: 'Data not found',
        IS_UPDATED_SUCCESSFULLY: 'is Updated Successfully!!!',
        ACTIVE_SUCCESSFULLY: 'active successfully!!!',
        ADDED_SUCCESSFULLY: 'added successfully!!!',
        DELETE_SUCCESSFULLY: 'deleted successfully!',
        IMG_UPLOAD_SUCCESSFULLY: 'image upload successfully',
        IMAGE_NOT_FOUND: 'Image not found',
        FAILED_ADDED_IMAGE: 'Fail to added image..!',
        IMAGE_DELETE_SUCCESSFULLY: 'Image deleted successfully',
        FOUND_SUCCESSFULLY: 'found Successfully',
        NOT_FOUND: 'not found',
        ERROR_OCCURRED:'Some error occurred while retrieving data',
        FOLLOW_SUCCESSFULLY: 'follow successfully ..!!!',
        UNFOLLOW_SUCCESSFULLY: 'unfollow successfully ..!!!',
        ALREADY_FOLLOWED:'you are already followed..!!!',
        U_MUST_FOLLOW_FIRST:'you must follow first..!!!',
        FAIL_TO_GET_EVENT_POINT:'Fail to get user eventPoints',
        FAIL_TO_UPDATE_EVENT_POINT:'Fail to update user eventPoints',
        INVALID_PRODUCT_ID:'Please enter valid product id ..!!',
        INVALID_BRAND_ID:'Please enter valid brand id ..!!',
        INVALID_CATEGORY_ID:'Please enter valid category id ..!!',
        INVALID_USER_ID:'Please enter valid user id ..!!',
        STATUS_UPDATE_SUCCESSFULLY:'status update succussfully ...!! '
    },
    COLLECTION: {
        USER: 'User ',
        CUSTOMER: 'Customer '
    },
    FOLDER_USER_IMG: "uploaded_documents/user_images/",
}